### ISSUE TITLE
draconic evolution chaos bolts D:

### ISSUE THREAD

**Issue by japherwocky** [japherwocky/japherpack#2]
```
[23:27:18] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking entity
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:642) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.NoClassDefFoundError: dan200/computercraft/shared/util/WorldUtil
at com.brandon3055.draconicevolution.common.entity.EntityChaosBolt.func_70071_h_(EntityChaosBolt.java:79) ~[EntityChaosBolt.class:?]
at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
... 4 more
Caused by: java.lang.ClassNotFoundException: dan200.computercraft.shared.util.WorldUtil
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.11.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_45]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_45]
at com.brandon3055.draconicevolution.common.entity.EntityChaosBolt.func_70071_h_(EntityChaosBolt.java:79) ~[EntityChaosBolt.class:?]
at net.minecraft.world.World.func_72866_a(World.java:2070) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648) ~[mt.class:?]
at net.minecraft.world.World.func_72870_g(World.java:2034) ~[ahb.class:?]
at net.minecraft.world.World.func_72939_s(World.java:1887) ~[ahb.class:?]
at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489) ~[mt.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636) ~[MinecraftServer.class:?]
... 4 more
Caused by: java.lang.NullPointerException
[23:27:18] [Server thread/ERROR]: This crash report has been saved to: ~./crash-reports/crash-2015-10-24_23.27.18-server.txt
[23:27:18] [Server thread/INFO]: Stopping server
Exception in thread "AE2 VersionChecker"
[NodePanel] Process offline
```

**Comment by superckl** [comment]
brandon3055/Draconic-Evolution#166
