### ISSUE TITLE
witchery way of time tracebacks

### ISSUE THREAD

**Issue by japherwocky** [japherwocky/japherpack#5]
```
[13:08:17] [Server thread/WARN]  [witchery: SERVER]: witchery: unhandled exception post init for hook AWWayofTime
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NoClassDefFoundError: WayofTime/alchemicalWizardry/api/soulNetwork/SoulNetworkHandler
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at com.emoniph.witchery.integration.ModHookBloodMagic$IntegrateBloodMagic.boostBloodPowers(ModHookBloodMagic.java:111)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at com.emoniph.witchery.integration.ModHookBloodMagic.boostBloodPowers(ModHookBloodMagic.java:58)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at com.emoniph.witchery.integration.ModHookManager.boostBloodPowers(ModHookManager.java:73)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at com.emoniph.witchery.infusion.infusions.symbols.EffectRegistry$1.perform(EffectRegistry.java:981)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.item.ItemStack.func_77974_b(ItemStack.java:402)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at com.emoniph.witchery.item.ItemMysticBranch.func_77615_a(ItemMysticBranch.java:193)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.entity.player.EntityPlayer.func_71034_by(EntityPlayer.java:196)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.network.NetHandlerPlayServer.func_147345_a(NetHandlerPlayServer.java:439)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:53)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.network.play.client.C07PacketPlayerDigging.func_148833_a(SourceFile:8)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.ClassNotFoundException: WayofTime.alchemicalWizardry.api.soulNetwork.SoulNetworkHandler
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: ... 17 more
[13:08:17] [Server thread/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: Caused by: java.lang.NullPointerException
```

**Comment by japherwocky** [comment]
possibly related? no idea, arak is streaming a different bug right now, so let's save the timestamp
